// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRaoAXguaxn6YtrcirAB59FRQUKAZOMXw',
    appId: '1:582875867905:web:45ac338e6c9299613ec900',
    messagingSenderId: '582875867905',
    projectId: 'sleeplesstalent',
    authDomain: 'sleeplesstalent.firebaseapp.com',
    storageBucket: 'sleeplesstalent.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWOV0Zdh1R_V-LkfHMuimYys5dxLIiIkQ',
    appId: '1:582875867905:android:59f554f5584d3b8c3ec900',
    messagingSenderId: '582875867905',
    projectId: 'sleeplesstalent',
    storageBucket: 'sleeplesstalent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAHA_RLctTDlZhYlTHKF35B4NgOwgRxSk',
    appId: '1:582875867905:ios:91fd339e84abe5d63ec900',
    messagingSenderId: '582875867905',
    projectId: 'sleeplesstalent',
    storageBucket: 'sleeplesstalent.appspot.com',
    iosBundleId: 'com.example.sleeplesstalented',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAHA_RLctTDlZhYlTHKF35B4NgOwgRxSk',
    appId: '1:582875867905:ios:91fd339e84abe5d63ec900',
    messagingSenderId: '582875867905',
    projectId: 'sleeplesstalent',
    storageBucket: 'sleeplesstalent.appspot.com',
    iosBundleId: 'com.example.sleeplesstalented',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRaoAXguaxn6YtrcirAB59FRQUKAZOMXw',
    appId: '1:582875867905:web:eebe33111ee488d63ec900',
    messagingSenderId: '582875867905',
    projectId: 'sleeplesstalent',
    authDomain: 'sleeplesstalent.firebaseapp.com',
    storageBucket: 'sleeplesstalent.appspot.com',
  );
}
